@startuml
skinparam classAttributeIconSize 0

interface Navigator {
    + setPosition(xCoordinate : int, yCoordinate : int, Heading heading) : boolean
    + getLocation() : String
    + spin(heading : SpinDirection) : void
    + move() : void
}

abstract class Rover extends Navigator  {
  - String roverId
  - int xPosition
  - int yPosition
  - Heading currentHeading

  + getRoverId() : String
}

class SurfaceRover implements Rover  {
    + SurfaceRover(capcom : NASACapcomService, roverId : String)
}

interface PlateauInterface  {
   + isValidCoordinate(xCoordinate : int, yCoordinate : int) : boolean
}

abstract class Plateau extends PlateauInterface {
  - String plateauId
  + getPlateauId() : String
}

class QuadPlateau implements Plateau {
  - int xMaximum
  - int yMaximum

   + QuadPlateau(plateauId : String, xMaximum : int, yMaximum : int)

}


enum Heading
{
NORTH
EAST
SOUTH
WEST
+ getHeadingInitial() : char
+ getNewHeading(direction : Direction) : HeadingEnum
+ getHeadingByInitial(heading : char) : HeadingEnum
}

enum Direction
{
LEFT
RIGHT
}

enum InstructionType
{
LEFT
RIGHT
MOVE
+ getInstructionType(instruction : String) : InstructionType
}

interface NASACapcomInterface {
  + processInstruction(instruction : String) : boolean
  + getStatusReport() : String
  + getPlateauList() : String
  + getRoverList() : String
  + isValidMove(roverId : String, xCoordinate : int, yCoordinate : int) : boolean
}

abstract class NASACapcom implements NASACapcomInterface {
  - Map<Rover, Plateau> roverMap;
  - List<Plateau> plateauList;

  - createPlateau(xMaximum : int, yMaximum : int) : void
  - createRover(roverId : String, plateau : Plateau, xCoordinate : int, yCoordinate : int, heading : char) : void
  - getRover() : Rover
  - getRover(roverId : String) : Rover
  - getPlateau(plateauId : String) : Plateau
  - getRoverStatus(roverId : String) : String
  - processSequence(roverId : String, sequence : String) : boolean
}

class NASACapcomService extends NASACapcom
{
}

NASACapcom - Plateau
Rover -- NASACapcomService


Heading -[hidden] Navigator
Heading -[hidden]d-> Direction
Direction -[hidden]d-> InstructionType

@enduml