@startuml
skinparam classAttributeIconSize 0

interface Navigator {
    + setPosition(capcom : NASACapcom, xCoordinate : int, yCoordinate : int, Heading heading) : boolean
    + getLocation() : String
    + spin(heading : SpinDirection) : void
    + move() : void
}

abstract class Rover extends Navigator  {
  # String roverId
  # NASACapcom capcom
  # int xPosition
  # int yPosition
  # Heading currentHeading

  + getRoverId() : String
}

class SurfaceRover implements Rover  {
    + SurfaceRover(capcom : NASACapcom, roverId : String)
}

interface PlateauInterface  {
   + isValidCoordinate(xCoordinate : int, yCoordinate : int) : boolean
}

abstract class Plateau extends PlateauInterface {
  - String plateauId
  + getPlateauId() : String
}

class QuadPlateau implements Plateau {
  - int xMaximum
  - int yMaximum

   + QuadPlateau(plateauId : String, xMaximum : int, yMaximum : int)
}


enum Heading
{
NORTH
EAST
SOUTH
WEST
+ getHeadingInitial() : char
+ getNewHeading(direction : Direction) : HeadingEnum
+ getByInitial(heading : char) : HeadingEnum
}

enum Direction
{
LEFT
RIGHT
}

enum InstructionType
{
LEFT
RIGHT
MOVE
+ getInstructionType(instruction : String) : InstructionType
}

interface NASACapcomInterface {
  + processInstruction(instruction : String) : boolean
  + getStatusReport() : String
  + isValidMove(roverId : String, xCoordinate : int, yCoordinate : int) : boolean
}

abstract class NASACapcom implements NASACapcomInterface {
  - Map<Rover, Plateau> roverMap;
  - List<Plateau> plateauList;
  - Plateau currentPlateau
  - Rover currentRover

  + processInstruction(instruction : String) : void
  + isValidMove(roverId : String, xCoordinate : int, yCoordinate : int) : boolean
  + getStatusReport() : String
  # createPlateau(xMaximum : int, yMaximum : int) : void
  # createRover(xCoordinate : int, yCoordinate : int, heading : HeadingEnum) : void
  # getRoverById(roverId : String) : Rover
  - isValidAndFreeCoordinate(plateau : Plateau, rover : Rover, xCoordinate : int, yCoordinate :int) : boolean
  - processMoveSequence(moveSequence : String) : void
}

class NASACapcomService extends NASACapcom
{
  + getPlateauList() : String
  + getRoverList() : String
}

NASACapcom - Plateau
Rover -- NASACapcomService


Heading -[hidden] Navigator
Heading -[hidden]d-> Direction
Direction -[hidden]d-> InstructionType

@enduml