@startuml
skinparam classAttributeIconSize 0

interface Navigator {
    + getLocation() : String
    + spin(callingCapcom : NASACapcom, heading : SpinDirection) : void
    + move(callingCapcom : NASACapcom) : void
}

abstract class Rover extends Navigator  {
  # String roverId
  # Plateau plateau
  # NASACapcom capcom
  # int xPosition
  # int yPosition
  # Heading currentHeading

  + getId() : String
  + getPlateau() : Plateau
}

class SurfaceRover implements Rover  {
    + SurfaceRover(capcom : NASACapcom, roverId : plateau : Plateau, String, xCoordinate : int, yCoordinate : int, heading : Heading)
}

interface PlateauInterface  {
   + isValidCoordinate(xCoordinate : int, yCoordinate : int) : boolean
   + getId() : String
   + getDimensions() : String
   + storeRoverPosition() : boolean
}

abstract class Plateau extends PlateauInterface {
  # String id
  # String dimensions
  # RoverDetails rovers
}

class QuadPlateau implements Plateau {
  - int xMaximum
  - int yMaximum

   + QuadPlateau(plateauId : String, xMaximum : int, yMaximum : int)
}


enum Heading
{
NORTH
EAST
SOUTH
WEST
+ getHeadingInitial() : char
+ getNewHeading(direction : Direction) : HeadingEnum
+ getByInitial(heading : char) : HeadingEnum
}

enum Direction
{
LEFT
RIGHT
}

enum InstructionType
{
CREATE_PLATEAU
CREATE_ROVER
MOVE
SWITCH_PLATEAU
SWITCH_ROVER
+ getInstructionType(instruction : String) : InstructionType
}

interface NASACapcomInterface {
  + processInstruction(instruction : String) : String
  + getStatusReport() : String
}

abstract class NASACapcom implements NASACapcomInterface {
  - Map<String, Rover> roverMap;
  - Map<String, Plateau> plateauMap;
  - Plateau currentPlateau
  - Rover currentRover

  + processInstruction(instruction : String) : String
  + getStatusReport() : String
  # createPlateau(xMaximum : int, yMaximum : int) : void
  # createRover(xCoordinate : int, yCoordinate : int, heading : HeadingEnum) : void
  # getPlateauById(PlateauId : String) : Plateau
  # getRoverById(roverId : String) : Rover
  - isValidAndFreeCoordinate(plateau : Plateau, rover : Rover, xCoordinate : int, yCoordinate :int) : boolean
  - processMoveSequence(moveSequence : String) : void
}

class NASACapcomService extends NASACapcom
{
  + getPlateauList() : String
  + getRoverList() : String
}

NASACapcomService -- Plateau
Rover -- NASACapcomService
Rover -- Plateau

Heading -[Hidden] Navigator
Heading -[hidden] Direction
Heading -[hidden]d-> InstructionType

@enduml